/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rxtxrobot_controls;

import java.awt.Color;
import java.awt.Point;
import java.io.PrintStream;
import javax.swing.JOptionPane;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import rxtxrobot.*;

/**
 *
 * @author raikia
 */
public final class MainWindow extends javax.swing.JFrame
{
        /**
         * Creates new form MainWindow
         */
        private Interaction main_obj;
        private static PrintStream outPs;
        private static PrintStream errPs;
        private static Style errStyle;
        private static Style outStyle;
        private Thread updateSerial;
        private Thread robotThread;

        public MainWindow()
        {
                outPs = new PrintStream(System.out)
                {
                        @Override
                        public void println(String x)
                        {
                                try
                                {
                                        verbose_output.getStyledDocument().insertString(verbose_output.getStyledDocument().getLength(), x + "\n", outStyle);
                                }
                                catch (Exception e)
                                {
                                        JOptionPane.showMessageDialog(null, "Failed System.out printing verbosely", "PrintStream failed", JOptionPane.ERROR_MESSAGE);
                                }
                        }
                };
                errPs = new PrintStream(System.out)
                {
                        @Override
                        public void println(String x)
                        {
                                try
                                {
                                        verbose_output.getStyledDocument().insertString(verbose_output.getStyledDocument().getLength(), x + "\n", errStyle);
                                }
                                catch (Exception e)
                                {
                                        JOptionPane.showMessageDialog(null, "Failed System.err printing verbosely", "PrintStream failed", JOptionPane.ERROR_MESSAGE);
                                }
                        }
                };
                String[] available_ports = SerialCommunication.checkValidPorts();
                initComponents();
                verbose_container.setVisible(false);
                this.pack();
                errStyle = verbose_output.addStyle("error", null);
                StyleConstants.setForeground(errStyle, Color.red);
                outStyle = verbose_output.addStyle("out", null);
                StyleConstants.setForeground(outStyle, Color.green);
                System.setOut(outPs);
                System.setErr(errPs);
                enableAll(false);
                updatePortList(available_ports);
                updateSerial = new Thread(new Refresh_Serial(this));
                updateSerial.start();
        }

        public void updatePortList()
        {
                String[] list = SerialCommunication.checkValidPorts();
                updatePortList(list);
        }

        private void updatePortList(String[] list)
        {
                port_model.removeAllElements();
                for (int x = 0; x < list.length; ++x)
                        port_model.addElement(list[x]);
        }

        private void notifyRobot()
        {
                synchronized (main_obj)
                {
                        main_obj.notify();
                }
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arduino_port = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        arduino_connect_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        connection_status = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        m1_speed = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        m1_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        m3_speed = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        m3_btn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        m2_speed = new javax.swing.JSlider();
        jLabel14 = new javax.swing.JLabel();
        m2_btn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        m4_speed = new javax.swing.JSlider();
        jLabel17 = new javax.swing.JLabel();
        m4_btn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        servo1_position = new javax.swing.JSlider();
        jLabel20 = new javax.swing.JLabel();
        servo1_btn = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        servo2_position = new javax.swing.JSlider();
        jLabel23 = new javax.swing.JLabel();
        servo2_btn = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        analog_textbox = new javax.swing.JTextField();
        analog_read_btn = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        digital_textbox = new javax.swing.JTextField();
        digital_read_btn = new javax.swing.JButton();
        start_all = new javax.swing.JButton();
        reset_all = new javax.swing.JButton();
        set_verbose_btn = new javax.swing.JToggleButton();
        verbose_container = new javax.swing.JScrollPane();
        verbose_output = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        quit_menuitem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        about_menuitem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RXTXRobot Controls");
        setResizable(false);

        port_model = new javax.swing.DefaultComboBoxModel();
        arduino_port.setModel(port_model);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel1.setText("Arduino Port: ");

        arduino_connect_btn.setText("Connect");
        arduino_connect_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arduino_connect_btn_actionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel2.setText("Status: ");

        connection_status.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        connection_status.setForeground(new java.awt.Color(255, 51, 51));
        connection_status.setText("Disconnected");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DC Motor 1"));

        jLabel4.setText("Motor Port:");

        m1_speed.setMajorTickSpacing(255);
        m1_speed.setMaximum(255);
        m1_speed.setMinimum(-255);
        m1_speed.setPaintLabels(true);
        m1_speed.setPaintTicks(true);
        m1_speed.setValue(0);

        jLabel5.setText("Speed");

        m1_btn.setText("Start");
        m1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dc_motor_1_actionPerformed(evt);
            }
        });

        jLabel6.setText("M1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(55, 55, 55)
                        .addComponent(m1_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(m1_speed, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(m1_btn)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m1_speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("DC Motor 3"));

        jLabel7.setText("Motor Port:");

        m3_speed.setMajorTickSpacing(255);
        m3_speed.setMaximum(255);
        m3_speed.setMinimum(-255);
        m3_speed.setPaintLabels(true);
        m3_speed.setPaintTicks(true);
        m3_speed.setValue(0);

        jLabel8.setText("Speed");

        m3_btn.setText("Start");
        m3_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dc_motor_3_actionPerformed(evt);
            }
        });

        jLabel9.setText("M3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(55, 55, 55)
                        .addComponent(m3_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(m3_speed, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(m3_btn)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m3_speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("DC Motor 2"));

        jLabel13.setText("Motor Port:");

        m2_speed.setMajorTickSpacing(255);
        m2_speed.setMaximum(255);
        m2_speed.setMinimum(-255);
        m2_speed.setPaintLabels(true);
        m2_speed.setPaintTicks(true);
        m2_speed.setValue(0);

        jLabel14.setText("Speed");

        m2_btn.setText("Start");
        m2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dc_motor_2_actionPerformed(evt);
            }
        });

        jLabel15.setText("M2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(55, 55, 55)
                        .addComponent(m2_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(m2_speed, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(m2_btn)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m2_speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("DC Motor 4"));

        jLabel16.setText("Motor Port:");

        m4_speed.setMajorTickSpacing(255);
        m4_speed.setMaximum(255);
        m4_speed.setMinimum(-255);
        m4_speed.setPaintLabels(true);
        m4_speed.setPaintTicks(true);
        m4_speed.setValue(0);

        jLabel17.setText("Speed");

        m4_btn.setText("Start");
        m4_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dc_motor_4_actionPerformed(evt);
            }
        });

        jLabel18.setText("M4");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addGap(55, 55, 55)
                        .addComponent(m4_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(m4_speed, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(m4_btn)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m4_speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Servo 1"));

        jLabel19.setText("Servo Port:");

        servo1_position.setMajorTickSpacing(90);
        servo1_position.setMaximum(180);
        servo1_position.setPaintLabels(true);
        servo1_position.setPaintTicks(true);
        servo1_position.setValue(90);

        jLabel20.setText("Position");

        servo1_btn.setText("Go");
        servo1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servo_1_actionPerformed(evt);
            }
        });

        jLabel21.setText("1");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(servo1_position, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(servo1_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(servo1_btn)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(servo1_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Servo 2"));

        jLabel22.setText("Servo Port:");

        servo2_position.setMajorTickSpacing(90);
        servo2_position.setMaximum(180);
        servo2_position.setPaintLabels(true);
        servo2_position.setPaintTicks(true);
        servo2_position.setValue(90);

        jLabel23.setText("Position");

        servo2_btn.setText("Go");
        servo2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servo_2_actionPerformed(evt);
            }
        });

        jLabel24.setText("2");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addGap(67, 67, 67)
                        .addComponent(servo2_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(servo2_position, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(servo2_btn)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(servo2_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Sensors"));

        jLabel25.setText("Analog Pins:");

        analog_textbox.setEditable(false);
        analog_textbox.setText("N/A");

        analog_read_btn.setText("Read");
        analog_read_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analog_read_btn_actionPerformed(evt);
            }
        });

        jLabel26.setText("Digital Pins:");

        digital_textbox.setEditable(false);
        digital_textbox.setText("N/A");

        digital_read_btn.setText("Read");
        digital_read_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digital_read_btn_actionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(analog_textbox, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(digital_textbox))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(analog_read_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(digital_read_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(analog_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(analog_read_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(digital_textbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(digital_read_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        start_all.setText("Start All");
        start_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_all_actionPerformed(evt);
            }
        });

        reset_all.setText("Reset All");
        reset_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_all_actionPerformed(evt);
            }
        });

        set_verbose_btn.setText("Verbose");
        set_verbose_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_verbose_btn_actionPerformed(evt);
            }
        });

        verbose_container.setBorder(null);

        verbose_output.setEditable(false);
        verbose_output.setBackground(new java.awt.Color(0, 0, 0));
        verbose_container.setViewportView(verbose_output);

        jMenu1.setText("File");

        quit_menuitem.setText("Quit");
        quit_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quit_menuitem_actionPerformed(evt);
            }
        });
        jMenu1.add(quit_menuitem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        about_menuitem.setText("About");
        about_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_menuitem_actionPerformed(evt);
            }
        });
        jMenu2.add(about_menuitem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(arduino_port, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(arduino_connect_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(connection_status)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(start_all, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reset_all, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(verbose_container)
                    .addComponent(set_verbose_btn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(arduino_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arduino_connect_btn)
                    .addComponent(jLabel2)
                    .addComponent(connection_status))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset_all)
                    .addComponent(start_all))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(set_verbose_btn)
                .addGap(18, 18, 18)
                .addComponent(verbose_container, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-767)/2, (screenSize.height-860)/2, 767, 860);
    }// </editor-fold>//GEN-END:initComponents

    private void arduino_connect_btn_actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arduino_connect_btn_actionPerformed
            if (arduino_connect_btn.getText().equalsIgnoreCase("connect"))
            {
                    if (arduino_port.getSelectedIndex() == -1)
                    {
                            JOptionPane.showMessageDialog(this, "No Arduino port was selected.", "Arduino Port Error", JOptionPane.ERROR_MESSAGE);
                            errPs.println("Error: No Arduino port was selected.");
                    }
                    else
                    {
                            System.out.println("Connecting to port: " + (String) arduino_port.getSelectedItem());
                            main_obj = new Interaction(this, (String) arduino_port.getSelectedItem(), outPs, errPs);
                            robotThread = new Thread(main_obj);
                            updateSerial.stop();
                            updateSerial = new Thread(new Refresh_Serial(this));
                            robotThread.start();
                    }
            }
            else
            {
                    main_obj.stopRunning();
                    notifyRobot();
                    updateSerial.start();
            }
    }//GEN-LAST:event_arduino_connect_btn_actionPerformed

        public void enableAll(boolean a)
        {
                m1_btn.setEnabled(a);
                m1_speed.setEnabled(a);
                m2_btn.setEnabled(a);
                m2_speed.setEnabled(a);
                m3_btn.setEnabled(a);
                m3_speed.setEnabled(a);
                m4_btn.setEnabled(a);
                m4_speed.setEnabled(a);
                analog_read_btn.setEnabled(a);
                digital_read_btn.setEnabled(a);
                reset_all.setEnabled(a);
                servo1_btn.setEnabled(a);
                servo1_position.setEnabled(a);
                servo2_btn.setEnabled(a);
                servo2_position.setEnabled(a);
                start_all.setEnabled(a);
        }
    private void set_verbose_btn_actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_verbose_btn_actionPerformed
            Point pre = this.getLocation();
            verbose_container.setVisible(set_verbose_btn.isSelected());
            this.pack();
            this.setLocation(pre);
            this.pack();
            //this.setLocation(pre);
    }//GEN-LAST:event_set_verbose_btn_actionPerformed

    private void dc_motor_1_actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dc_motor_1_actionPerformed
            if (m1_btn.getText().equalsIgnoreCase("start"))
            {
                    m1_btn.setText("Stop");
                    main_obj.execute(Interaction.RUN_MOTOR, RXTXRobot.MOTOR1, m1_speed.getValue(), 0);
            }
            else
            {
                    m1_btn.setText("Start");
                    main_obj.execute(Interaction.RUN_MOTOR, RXTXRobot.MOTOR1, 0, 0);
            }
            notifyRobot();
    }//GEN-LAST:event_dc_motor_1_actionPerformed

    private void dc_motor_2_actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dc_motor_2_actionPerformed
            if (m2_btn.getText().equalsIgnoreCase("start"))
            {
                    m2_btn.setText("Stop");
                    main_obj.execute(Interaction.RUN_MOTOR, RXTXRobot.MOTOR1, m2_speed.getValue(), 0);
            }
            else
            {
                    m2_btn.setText("Start");
                    main_obj.execute(Interaction.RUN_MOTOR, RXTXRobot.MOTOR1, 0, 0);
            }
            notifyRobot();
    }//GEN-LAST:event_dc_motor_2_actionPerformed

    private void dc_motor_3_actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dc_motor_3_actionPerformed
            if (m3_btn.getText().equalsIgnoreCase("start"))
            {
                    m3_btn.setText("Stop");
                    main_obj.execute(Interaction.RUN_MOTOR, RXTXRobot.MOTOR3, m3_speed.getValue(), 0);
            }
            else
            {
                    m3_btn.setText("Start");
                    main_obj.execute(Interaction.RUN_MOTOR, RXTXRobot.MOTOR3, 0, 0);
            }
            notifyRobot();
    }//GEN-LAST:event_dc_motor_3_actionPerformed

    private void dc_motor_4_actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dc_motor_4_actionPerformed
            if (m4_btn.getText().equalsIgnoreCase("start"))
            {
                    m4_btn.setText("Stop");
                    main_obj.execute(Interaction.RUN_MOTOR, RXTXRobot.MOTOR4, m4_speed.getValue(), 0);
            }
            else
            {
                    m4_btn.setText("Start");
                    main_obj.execute(Interaction.RUN_MOTOR, RXTXRobot.MOTOR4, 0, 0);
            }
            notifyRobot();
    }//GEN-LAST:event_dc_motor_4_actionPerformed

    private void servo_1_actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servo_1_actionPerformed
            main_obj.execute(Interaction.MOVE_SERVO, RXTXRobot.SERVO1, servo1_position.getValue());
            notifyRobot();
    }//GEN-LAST:event_servo_1_actionPerformed

    private void servo_2_actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servo_2_actionPerformed
            main_obj.execute(Interaction.MOVE_SERVO, RXTXRobot.SERVO2, servo2_position.getValue());
            notifyRobot();
    }//GEN-LAST:event_servo_2_actionPerformed

    private void analog_read_btn_actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analog_read_btn_actionPerformed
            main_obj.execute(Interaction.READ_ANALOG);
            notifyRobot();
    }//GEN-LAST:event_analog_read_btn_actionPerformed

    private void digital_read_btn_actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digital_read_btn_actionPerformed
            main_obj.execute(Interaction.READ_DIGITAL);
            notifyRobot();
    }//GEN-LAST:event_digital_read_btn_actionPerformed

    private void start_all_actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_all_actionPerformed
            m1_btn.setText("Stop");
            main_obj.execute(Interaction.RUN_MOTOR, RXTXRobot.MOTOR1, m1_speed.getValue(), 0);
            m2_btn.setText("Stop");
            main_obj.execute(Interaction.RUN_MOTOR, RXTXRobot.MOTOR2, m2_speed.getValue(), 0);
            m3_btn.setText("Stop");
            main_obj.execute(Interaction.RUN_MOTOR, RXTXRobot.MOTOR3, m3_speed.getValue(), 0);
            m4_btn.setText("Stop");
            main_obj.execute(Interaction.RUN_MOTOR, RXTXRobot.MOTOR4, m4_speed.getValue(), 0);
            main_obj.execute(Interaction.MOVE_SERVO, RXTXRobot.SERVO1, servo1_position.getValue());
            main_obj.execute(Interaction.MOVE_SERVO, RXTXRobot.SERVO2, servo2_position.getValue());
            notifyRobot();
    }//GEN-LAST:event_start_all_actionPerformed

    private void reset_all_actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_all_actionPerformed

            m1_btn.setText("Start");
            main_obj.execute(Interaction.RUN_MOTOR, RXTXRobot.MOTOR1, 0, 0);
            m2_btn.setText("Start");
            main_obj.execute(Interaction.RUN_MOTOR, RXTXRobot.MOTOR2, 0, 0);
            m3_btn.setText("Start");
            main_obj.execute(Interaction.RUN_MOTOR, RXTXRobot.MOTOR3, 0, 0);
            m4_btn.setText("Start");
            main_obj.execute(Interaction.RUN_MOTOR, RXTXRobot.MOTOR4, 0, 0);
            m1_speed.setValue(0);
            m2_speed.setValue(0);
            m3_speed.setValue(0);
            m4_speed.setValue(0);
            servo1_position.setValue(90);
            servo2_position.setValue(90);
            main_obj.execute(Interaction.MOVE_SERVO, RXTXRobot.SERVO1, 90);
            main_obj.execute(Interaction.MOVE_SERVO, RXTXRobot.SERVO2, 90);
            analog_textbox.setText("N/A");
            digital_textbox.setText("N/A");
            notifyRobot();
    }//GEN-LAST:event_reset_all_actionPerformed

    private void about_menuitem_actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_menuitem_actionPerformed
            JOptionPane.showMessageDialog(this, "This tool was written by:\n\nChris King <ccking@smu.edu>\n\nhttp://lyle.smu.edu/fyd", "About this tool", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_about_menuitem_actionPerformed

    private void quit_menuitem_actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quit_menuitem_actionPerformed
            if (JOptionPane.showConfirmDialog(this, "Are you sure you want to quit?", "Confirm Exit", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION)
            {
                    this.dispose();
                    System.exit(0);
            }
    }//GEN-LAST:event_quit_menuitem_actionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about_menuitem;
    private javax.swing.JButton analog_read_btn;
    public javax.swing.JTextField analog_textbox;
    public javax.swing.JButton arduino_connect_btn;
    private javax.swing.JComboBox arduino_port;
    public javax.swing.JLabel connection_status;
    private javax.swing.JButton digital_read_btn;
    public javax.swing.JTextField digital_textbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton m1_btn;
    private javax.swing.JSlider m1_speed;
    private javax.swing.JButton m2_btn;
    private javax.swing.JSlider m2_speed;
    private javax.swing.JButton m3_btn;
    private javax.swing.JSlider m3_speed;
    private javax.swing.JButton m4_btn;
    private javax.swing.JSlider m4_speed;
    private javax.swing.JMenuItem quit_menuitem;
    private javax.swing.JButton reset_all;
    private javax.swing.JButton servo1_btn;
    private javax.swing.JSlider servo1_position;
    private javax.swing.JButton servo2_btn;
    private javax.swing.JSlider servo2_position;
    private javax.swing.JToggleButton set_verbose_btn;
    private javax.swing.JButton start_all;
    private javax.swing.JScrollPane verbose_container;
    private javax.swing.JTextPane verbose_output;
    // End of variables declaration//GEN-END:variables
        private javax.swing.DefaultComboBoxModel<String> port_model;
}
